"""initial schema

Revision ID: 787f7027800c
Revises: 
Create Date: 2026-09-13 12:31:20.817368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '787f7027800c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_predictions_created_at'), table_name='predictions')
    op.drop_index(op.f('idx_predictions_search_id'), table_name='predictions')
    op.drop_index(op.f('idx_predictions_sentiment'), table_name='predictions')
    op.drop_column('predictions', 'metadata')
    op.drop_column('predictions', 'confidence')
    op.drop_index(op.f('idx_searches_user_id'), table_name='searches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_searches_user_id'), 'searches', ['user_id'], unique=False)
    op.add_column('predictions', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_predictions_sentiment'), 'predictions', ['sentiment'], unique=False)
    op.create_index(op.f('idx_predictions_search_id'), 'predictions', ['search_id'], unique=False)
    op.create_index(op.f('idx_predictions_created_at'), 'predictions', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('predictions', 'metadata_json')
    op.drop_column('predictions', 'sentiment_score')
    # ### end Alembic commands ###
